import { PlanDefinition, SubscriptionTier } from './types.js';

export const SUBSCRIPTION_PLANS: Record<SubscriptionTier, PlanDefinition> = {
  personal: {
    planId: 'personal',
    displayName: 'Personal',
    pricePlaceholder: '$39.00 / year',
    billingPeriod: 'annual',
    maxDevices: 1,
    offlineGracePeriodDays: 7,
    status: 'ACTIVE',
    description: 'Essential diagnostics and core repair utilities for personal computing environments.',
    entitlements: [
      'diagnostics.basic',
      'diagnostics.hardware',
      'repair.basic',
      'repair.registry',
      'repair.disk_cleanup',
      'performance.basic',
      'software.winget_basic',
      'network.diagnostics',
      'security.defender_status',
      'reports.basic_html'
    ]
  },
  professional: {
    planId: 'professional',
    displayName: 'Professional',
    pricePlaceholder: '$79.00 / year',
    billingPeriod: 'annual',
    maxDevices: 2,
    offlineGracePeriodDays: 7,
    status: 'ACTIVE',
    description: 'Comprehensive toolkit for power users, dual-workstation pros, and home labs.',
    entitlements: [
      'diagnostics.basic',
      'diagnostics.hardware',
      'diagnostics.deep_benchmarks',
      'diagnostics.system_twin',
      'repair.basic',
      'repair.registry',
      'repair.disk_cleanup',
      'repair.deep_wmi',
      'repair.dism_sfc',
      'repair.one_click_super',
      'performance.basic',
      'performance.pro_tweaks',
      'software.winget_basic',
      'software.bulk_installer',
      'software.debloat_pro',
      'network.diagnostics',
      'network.adapter_reset',
      'network.dns_flush',
      'security.defender_status',
      'security.hardening_pro',
      'security.tamper_guard',
      'ai.copilot_diagnostics',
      'ai.powershell_generator',
      'reports.basic_html',
      'reports.json_export',
      'reports.system_twin_export'
    ]
  },
  technician: {
    planId: 'technician',
    displayName: 'Technician',
    pricePlaceholder: '$149.00 / year',
    billingPeriod: 'annual',
    maxDevices: 5,
    offlineGracePeriodDays: 14,
    status: 'ACTIVE',
    description: 'Field technician grade toolkit with extended offline tolerance, 5 device seats, and client report generator.',
    entitlements: [
      'diagnostics.basic',
      'diagnostics.hardware',
      'diagnostics.deep_benchmarks',
      'diagnostics.system_twin',
      'diagnostics.event_log_analyzer',
      'repair.basic',
      'repair.registry',
      'repair.disk_cleanup',
      'repair.deep_wmi',
      'repair.dism_sfc',
      'repair.one_click_super',
      'repair.driver_store_purge',
      'repair.printer_analyzer_pro',
      'performance.basic',
      'performance.pro_tweaks',
      'performance.ram_cache_purge',
      'software.winget_basic',
      'software.bulk_installer',
      'software.debloat_pro',
      'software.custom_bundles',
      'network.diagnostics',
      'network.adapter_reset',
      'network.dns_flush',
      'network.port_scanner',
      'security.defender_status',
      'security.hardening_pro',
      'security.tamper_guard',
      'security.bitlocker_audit',
      'ai.copilot_diagnostics',
      'ai.powershell_generator',
      'ai.automated_troubleshooter',
      'reports.basic_html',
      'reports.json_export',
      'reports.system_twin_export',
      'reports.client_branded_pdf',
      'reports.benchmarking_history',
      'technician.portable_mode',
      'technician.multi_client_profiles',
      'technician.offline_extended_grace'
    ]
  },
  business: {
    planId: 'business',
    displayName: 'Business & MSP Fleet',
    pricePlaceholder: '$399.00 / year',
    billingPeriod: 'annual',
    maxDevices: 25,
    offlineGracePeriodDays: 14,
    status: 'ACTIVE',
    description: 'Enterprise & IT Fleet management with 25 device activations, central policy synchronization, and audit logging.',
    entitlements: [
      'diagnostics.basic',
      'diagnostics.hardware',
      'diagnostics.deep_benchmarks',
      'diagnostics.system_twin',
      'diagnostics.event_log_analyzer',
      'diagnostics.fleet_telemetry',
      'repair.basic',
      'repair.registry',
      'repair.disk_cleanup',
      'repair.deep_wmi',
      'repair.dism_sfc',
      'repair.one_click_super',
      'repair.driver_store_purge',
      'repair.printer_analyzer_pro',
      'repair.mass_automation',
      'performance.basic',
      'performance.pro_tweaks',
      'performance.ram_cache_purge',
      'software.winget_basic',
      'software.bulk_installer',
      'software.debloat_pro',
      'software.custom_bundles',
      'software.fleet_package_push',
      'network.diagnostics',
      'network.adapter_reset',
      'network.dns_flush',
      'network.port_scanner',
      'security.defender_status',
      'security.hardening_pro',
      'security.tamper_guard',
      'security.bitlocker_audit',
      'security.fleet_compliance_check',
      'ai.copilot_diagnostics',
      'ai.powershell_generator',
      'ai.automated_troubleshooter',
      'ai.fleet_anomaly_detection',
      'reports.basic_html',
      'reports.json_export',
      'reports.system_twin_export',
      'reports.client_branded_pdf',
      'reports.benchmarking_history',
      'technician.portable_mode',
      'technician.multi_client_profiles',
      'technician.offline_extended_grace',
      'business.central_policy_sync',
      'business.fleet_audit_logs',
      'business.unattended_cli_execution'
    ]
  }
};
